AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'app/assets/javascripts/node_modules/**/*'
    - 'Vagrantfile'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 16

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded
